### ISSUE TITLE
Missing edges when using Docker's IPAM driver

### ISSUE THREAD

**Issue by idcrosby** [weaveworks/scope#1563]
Scope is not displaying some connections while we are running continuous load through our application.

Specifically, the front-end service is only shown as having one outbound connection, to the catalogue service. In fact it is communicating with the login, orders, accounts, and carts services as well. I have verified this via our log files.

Please ping me if you need any additional information.

[weave_report_and_svg.zip](https://github.com/weaveworks/scope/files/304731/weave_report_and_svg.zip)

**Comment by idcrosby** [comment]
It seems like Scope is not identifying the full weave IP range as local.

For instance, in the following report: [report_fons.json.gz](https://github.com/weaveworks/scope/files/305388/report_fons.json.gz)

We have a connection from 10.0.2.13:35096 to 10.0.2.8:80 (from frontend to accounts) which is not reflected in the UI

<img width="262" alt="screen shot 2016-06-08 at 18 51 14" src="https://cloud.githubusercontent.com/assets/1084449/15904716/06e7f93a-2daa-11e6-8004-047c7386b100.png">


The local networks don't contain that range

<img width="459" alt="screen shot 2016-06-08 at 18 53 46" src="https://cloud.githubusercontent.com/assets/1084449/15904820/5e91a01e-2daa-11e6-86a8-b3bdc4411958.png">


I'm using weave net 1.5.1 and here's the report from one of the nodes: 
[weave-report.json.gz](https://github.com/weaveworks/scope/files/305396/weave-report.json.gz)


weave's IPAM range is reported as:

```json
    "IPAM": {                                                                                   
        "Paxos": null,                                                                          
        "Range": "10.32.0.0-10.47.255.255",                                                     
        "RangeNumIPs": 1048576,                                                                 
        "DefaultSubnet": "10.32.0.0/12",                                                        
        "Entries": [                                                                            
            {                                                                                   
                "Token": "10.32.0.0",                                                           
                "Size": 1048576,                                                                
                "Peer": "fa:7e:27:1f:dd:08",                                                    
                "Nickname": "swarm-master",                                                     
                "IsKnownPeer": true,                                                            
                "Version": 1                                                                    
            }                                                                                   
        ],                                                                                      
        "PendingClaims": null,                                                                  
        "PendingAllocates": null                                                                
    },
```

**Comment by 2opremio** [comment]
Related: https://github.com/weaveworks/scope/issues/1162

**Comment by 2opremio** [comment]
The report does contain overlay local networks which are taken into account for creating edges:

<img width="305" alt="screen shot 2016-06-09 at 12 23 16 pm" src="https://cloud.githubusercontent.com/assets/2362916/15928141/1547ab5e-2e3d-11e6-80e9-51afa616b34e.png">

(the report provides an identical network for all nodes)

However ... isn't 10.0.2.8 out of 10.32.0.0/12? What am I missing?

**Comment by squaremo** [comment]
> However ... isn't 10.0.2.8 out of 10.32.0.0/12? What am I missing?

The IP addresses for the containers are supplied by Docker, because they are each declared part of a docker network, and docker wants to allocate the addresses on its networks.

Weave's IPAM cannot be used, because the plugin doesn't support more than one docker network in that mode.

**Comment by 2opremio** [comment]
The hacky workaround was to enforce IPAM subnets (10.32.0.0/13 and 10.40.0.0/13) overlapping the default Weave IPAM net.

The real solution is for Scope to get networking information from Docker and add local networks to the Overlay topology.

**Comment by rade** [comment]
> Weave's IPAM cannot be used, because the plugin doesn't support more than one docker network in that mode.

nitpick: Weave's IPAM *can* be used, but one would need to feed subnet info to `docker network create` to get allocations in different subnets. That is a worse user experience than using Docker's IPAM, so there is no point choosing that path.

(This doesn't alter the substance of this bug)

**Comment by tomwilkie** [comment]
@2opremio was this fixed by #1578?

**Comment by 2opremio** [comment]
No, this requires going through the docker networks to figure out their scope.

**Comment by idcrosby** [comment]
Pulled latest Scope image and still seeing the issue. Attaching report.

[scopeBug.zip](https://github.com/weaveworks/scope/files/317068/scopeBug.zip)

**Comment by 2opremio** [comment]
Reopening since it still happens when using global networks.
