### ISSUE TITLE
Deadlock in probe reporter

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#881]
I started the [ECS demo](http://www.weave.works/guides/service-discovery-and-load-balancing-with-weave-on-amazon-ecs-2/) with the 0.12 candidate and let it run overnight. When I checked its state in the morning all the Scope UIs were empty and the probes were all consuming a lot of memory.

The demo uses 3 hosts with Scope running in Standalone mode. Unfortunately, the probes weren't run with `--probe.http.listen` so I don't have Golang memory consumption details. This is the Virtual/RSS memory consumption of the probe running on each host:

* Probe A:  1108MB/597MB
* Probe B: 592MB/218MB
* Probe C: 657MB/356MB

As I said, the Scope UIs in all hosts are empty, indicating that apart from consuming a lot of memory they are not functioning properly. Here are the logs of Probe C:

https://gist.github.com/2opremio/9414979902b50ded7245

Around 4:30 the machine starts to run out of memory and around 4:50 the probe was killed but didn't recover gracefully. Other machines have similar logs, with machine A having experienced several restart so this seems like a leak.

The restarts are not graceful since the UI is empty in all hosts

I would say there are two problems:

* The high memory consumption/leak
* The probes not recovering gracefully when they are killed.

I will leave the probes running for a while in case it's not reproducible and spin up another demo with `--probe.http.listen` to try to reproduce and get detailed memory debugging information.

**Comment by 2opremio** [comment]
I have added the debug output of SIGQUIT and SIGUSR1 handlers of Probe C at the end of https://gist.github.com/2opremio/9414979902b50ded7245

It's not a goroutine leak and `alloc_bytes': 354030016.000` which matches the RSS I observed

**Comment by 2opremio** [comment]
After reproducing in a separate cluster with `--probe.http.listen` one of the probes is at ~100MB allocations (RSS is at 255MB).

Heap profile: http://filebin.ca/2V8LhzSwijC4/pprof.localhost9999.inuse_objects.inuse_space.003.pb.gz

![probe_heap_profile](https://cloud.githubusercontent.com/assets/2362916/12677475/3dd33476-c691-11e5-980e-6b9b36aa51c0.png)

**Comment by 2opremio** [comment]
I am not super familiar with this part of the code, but it seems like [c.pendingStats](https://github.com/weaveworks/scope/blob/6b5647576642555d91ff42f3d15b500ff818b308/probe/docker/container.go#L213) is growing out of control.

**Comment by 2opremio** [comment]
Running pprof against the binary and doing `sudo ln -s /go $GOPATH` (because the binary was built with $GOPATH pointing there and for some reason pprof expects sources to be in the very same location)  I get the following source information:

```
$ go tool pprof scope-probe ~/pprof/pprof.localhost\:9999.inuse_objects.inuse_space.003.pb.gz  
Entering interactive mode (type "help" for commands)
(pprof) top5
95.07MB of 105.65MB total (89.99%)
Dropped 464 nodes (cum <= 0.53MB)
Showing top 5 nodes out of 50 (cum >= 3.50MB)
      flat  flat%   sum%        cum   cum%
   58.56MB 55.43% 55.43%    58.56MB 55.43%  reflect.unsafe_NewArray
      14MB 13.25% 68.68%       14MB 13.25%  encoding/json.(*decodeState).literalStore
   13.51MB 12.79% 81.47%    81.06MB 76.73%  github.com/weaveworks/scope/probe/docker.(*container).StartGatheringStats.func1
    5.50MB  5.21% 86.68%     5.50MB  5.21%  reflect.mapassign
    3.50MB  3.31% 89.99%     3.50MB  3.31%  encoding/xml.copyValue
(pprof) list StartGatheringStats.func1   
Total: 105.65MB
ROUTINE ======================== github.com/weaveworks/scope/probe/docker.(*container).StartGatheringStats.func1 in /go/src/github.com/weaveworks/scope/probe/docker/container.go
   13.51MB    81.06MB (flat, cum) 76.73% of Total
         .          .    200:           }()
         .          .    201:
         .          .    202:           stats := &docker.Stats{}
         .          .    203:           decoder := json.NewDecoder(resp.Body)
         .          .    204:
         .    67.55MB    205:           for err := decoder.Decode(&stats); err != io.EOF; err = decoder.Decode(&stats) {
         .          .    206:                   if err != nil {
         .          .    207:                           log.Printf("docker container: error reading event, did container stop? %v", err)
         .          .    208:                           return
         .          .    209:                   }
         .          .    210:
         .          .    211:                   c.Lock()
         .          .    212:                   c.latestStats = stats
         .          .    213:                   c.pendingStats = append(c.pendingStats, stats)
         .          .    214:                   c.Unlock()
         .          .    215:
   13.51MB    13.51MB    216:                   stats = &docker.Stats{}
         .          .    217:           }
         .          .    218:   }()
         .          .    219:
         .          .    220:   return nil
         .          .    221:}
(pprof)
```

This suggests the error comes from `decoder.Decode()` and `stats = &docker.Stats{}` which I cannot really understand.

**Comment by tomwilkie** [comment]
I think this is fixed by 34447fd and 68a3748

I now get:

```
Toms-MacBook-Pro:scope twilkie$ make shell SUDO=
weave@host26-rack17:~$ go tool pprof prog/scope http://localhost:4041/debug/pprof/heap
Fetching profile from http://localhost:4041/debug/pprof/heap
Saved profile in /go/src/github.com/weaveworks/scope/pprof/pprof.scope.localhost:4041.inuse_objects.inuse_space.001.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
7.90MB of 15.47MB total (51.11%)
Dropped 338 nodes (cum <= 0.08MB)
Showing top 5 nodes out of 126 (cum >= 1.50MB)
      flat  flat%   sum%        cum   cum%
    2.51MB 16.21% 16.21%     2.51MB 16.21%  github.com/weaveworks/scope/vendor/github.com/coocood/freecache.NewCache
    1.79MB 11.59% 27.79%     1.79MB 11.59%  compress/flate.(*compressor).init
    1.45MB  9.37% 37.16%     1.45MB  9.37%  bytes.makeSlice
    1.16MB  7.48% 44.64%     1.16MB  7.48%  github.com/weaveworks/scope/vendor/github.com/weaveworks/weave/common.SignalHandlerLoop
       1MB  6.47% 51.11%     1.50MB  9.71%  crypto/x509.parseCertificate
(pprof) list StartGatheringStats.func1
Total: 15.47MB
ROUTINE ======================== github.com/weaveworks/scope/probe/docker.(*container).StartGatheringStats.func1 in /go/src/github.com/weaveworks/scope/probe/docker/container.go
  512.34kB        1MB (flat, cum)  6.47% of Total
         .          .    171:		if err != nil {
         .          .    172:			log.Printf("docker container: %v", err)
         .          .    173:			return
         .          .    174:		}
         .          .    175:
         .   512.05kB    176:		dial, err := DialStub(url.Scheme, url.Path)
         .          .    177:		if err != nil {
         .          .    178:			log.Printf("docker container: %v", err)
         .          .    179:			return
         .          .    180:		}
         .          .    181:
         .          .    182:		conn := NewClientConnStub(dial, nil)
         .          .    183:		resp, err := conn.Do(req)
         .          .    184:		if err != nil {
         .          .    185:			log.Printf("docker container: %v", err)
         .          .    186:			return
         .          .    187:		}
         .          .    188:		defer resp.Body.Close()
         .          .    189:
         .          .    190:		c.Lock()
         .          .    191:		c.statsConn = conn
         .          .    192:		c.Unlock()
         .          .    193:
         .          .    194:		defer func() {
         .          .    195:			c.Lock()
         .          .    196:			defer c.Unlock()
         .          .    197:
         .          .    198:			log.Printf("docker container: stopped collecting stats for %s", c.container.ID)
         .          .    199:			c.statsConn = nil
         .          .    200:		}()
         .          .    201:
  512.34kB   512.34kB    202:		var stats docker.Stats
         .          .    203:		decoder := json.NewDecoder(resp.Body)
         .          .    204:		for err := decoder.Decode(&stats); err != io.EOF; err = decoder.Decode(&stats) {
         .          .    205:			if err != nil {
         .          .    206:				log.Printf("docker container: error reading event, did container stop? %v", err)
         .          .    207:				return
         .          .    208:			}
         .          .    209:
```

I'll leave it running and gather more stats in an hour or so.

**Comment by tomwilkie** [comment]
Exactly the same memory usage after an hour.  I'm going to release.

**Comment by 2opremio** [comment]
Thanks @tomwilkie. I tested your fixes (68a3748) but unfortunately the main problem still persists. After a few hours running, the memory consumption (Virtual/RSS) of the probes is very high.

* A: 913MB/484MB
* B: 452MB/80MB
* C: 468MB/103MB

Also, this still results in empty Apps UIs which is more worrisome.

Here's the heap profile for Probe A: http://filebin.ca/2VP2tpSPMXj7/pprof.localhost9999.inuse_objects.inuse_space.001.pb.gz

![onewmoretime](https://cloud.githubusercontent.com/assets/2362916/12705899/f5ee6a68-c870-11e5-8174-2ec16390adda.png)

```
$ go tool pprof scope-probe /Users/fons/pprof/pprof.localhost:9999.inuse_objects.inuse_space.001.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
243.60MB of 258.55MB total (94.22%)
Dropped 514 nodes (cum <= 1.29MB)
Showing top 5 nodes out of 52 (cum >= 4.74MB)
      flat  flat%   sum%        cum   cum%
  160.64MB 62.13% 62.13%   160.64MB 62.13%  reflect.unsafe_NewArray
      34MB 13.15% 75.28%       34MB 13.15%  encoding/xml.copyValue
   22.23MB  8.60% 83.88%    22.23MB  8.60%  github.com/weaveworks/scope/probe/endpoint.(*conntrackWalker).handleFlow
      22MB  8.51% 92.39%       22MB  8.51%  encoding/xml.(*Decoder).name
    4.74MB  1.83% 94.22%     4.74MB  1.83%  compress/flate.(*compressor).init
(pprof) top10 -cum
194.64MB of 258.55MB total (75.28%)
Dropped 514 nodes (cum <= 1.29MB)
Showing top 10 nodes out of 52 (cum >= 34MB)
      flat  flat%   sum%        cum   cum%
         0     0%     0%   258.05MB 99.81%  runtime.goexit
         0     0%     0%   239.86MB 92.77%  github.com/weaveworks/scope/probe/endpoint.(*conntrackWalker).loop
         0     0%     0%   239.86MB 92.77%  github.com/weaveworks/scope/probe/endpoint.(*conntrackWalker).run
         0     0%     0%   217.64MB 84.18%  encoding/xml.(*Decoder).Decode
         0     0%     0%   217.64MB 84.18%  encoding/xml.(*Decoder).DecodeElement
         0     0%     0%   217.64MB 84.18%  encoding/xml.(*Decoder).unmarshal
         0     0%     0%   204.14MB 78.95%  encoding/xml.(*Decoder).unmarshalPath
         0     0%     0%   160.64MB 62.13%  reflect.MakeSlice
  160.64MB 62.13% 62.13%   160.64MB 62.13%  reflect.unsafe_NewArray
      34MB 13.15% 75.28%       34MB 13.15%  encoding/xml.copyValue
(pprof) list handleFlow
Total: 258.55MB
ROUTINE ======================== github.com/weaveworks/scope/probe/endpoint.(*conntrackWalker).handleFlow in /go/src/github.com/weaveworks/scope/probe/endpoint/conntrack.go
   22.23MB    22.23MB (flat, cum)  8.60% of Total
         .          .    308:	case forceAdd || f.Type == newType || f.Type == updateType:
         .          .    309:		if f.Independent.State != timeWait {
         .          .    310:			c.activeFlows[f.Independent.ID] = f
         .          .    311:		} else if _, ok := c.activeFlows[f.Independent.ID]; ok {
         .          .    312:			delete(c.activeFlows, f.Independent.ID)
   13.55MB    13.55MB    313:			c.bufferedFlows = append(c.bufferedFlows, f)
         .          .    314:		}
         .          .    315:	case f.Type == destroyType:
         .          .    316:		if _, ok := c.activeFlows[f.Independent.ID]; ok {
         .          .    317:			delete(c.activeFlows, f.Independent.ID)
    8.67MB     8.67MB    318:			c.bufferedFlows = append(c.bufferedFlows, f)
         .          .    319:		}
         .          .    320:	}
         .          .    321:}
         .          .    322:
         .          .    323:// walkFlows calls f with all active flows and flows that have come and gone
(pprof) list run
Total: 258.55MB
ROUTINE ======================== github.com/weaveworks/scope/probe/endpoint.(*conntrackWalker).run in /go/src/github.com/weaveworks/scope/probe/endpoint/conntrack.go
         0   239.86MB (flat, cum) 92.77% of Total
         .          .    164:}
         .          .    165:
         .          .    166:func (c *conntrackWalker) run() {
         .          .    167:	// Fork another conntrack, just to capture existing connections
         .          .    168:	// for which we don't get events
         .          .    169:	existingFlows, err := c.existingConnections()
         .          .    170:	if err != nil {
         .          .    171:		log.Printf("conntrack existingConnections error: %v", err)
         .          .    172:		return
         .          .    173:	}
         .          .    174:	for _, flow := range existingFlows {
         .          .    175:		c.handleFlow(flow, true)
         .          .    176:	}
         .          .    177:
         .          .    178:	args := append([]string{"-E", "-o", "xml", "-p", "tcp"}, c.args...)
         .          .    179:	cmd := exec.Command("conntrack", args...)
         .          .    180:	stdout, err := cmd.StdoutPipe()
         .          .    181:	if err != nil {
         .          .    182:		log.Printf("conntrack error: %v", err)
         .          .    183:		return
         .          .    184:	}
         .          .    185:
         .          .    186:	stderr, err := cmd.StderrPipe()
         .          .    187:	if err != nil {
         .          .    188:		log.Printf("conntrack error: %v", err)
         .          .    189:		return
         .          .    190:	}
         .          .    191:	go logPipe("conntrack stderr:", stderr)
         .          .    192:
         .          .    193:	if err := cmd.Start(); err != nil {
         .          .    194:		log.Printf("conntrack error: %v", err)
         .          .    195:		return
         .          .    196:	}
         .          .    197:
         .          .    198:	defer func() {
         .          .    199:		if err := cmd.Wait(); err != nil {
         .          .    200:			log.Printf("conntrack error: %v", err)
         .          .    201:		}
         .          .    202:	}()
         .          .    203:
         .          .    204:	c.Lock()
         .          .    205:	// We may have stopped in the mean time,
         .          .    206:	// so check to see if the channel is open
         .          .    207:	// under the lock.
         .          .    208:	select {
         .          .    209:	default:
         .          .    210:	case <-c.quit:
         .          .    211:		return
         .          .    212:	}
         .          .    213:	c.cmd = cmd
         .          .    214:	c.Unlock()
         .          .    215:
         .          .    216:	// Swallow the first two lines
         .          .    217:	reader := bufio.NewReader(stdout)
         .          .    218:	if line, err := reader.ReadString('\n'); err != nil {
         .          .    219:		log.Printf("conntrack error: %v", err)
         .          .    220:		return
         .          .    221:	} else if line != xmlHeader {
         .          .    222:		log.Printf("conntrack invalid output: '%s'", line)
         .          .    223:		return
         .          .    224:	}
         .          .    225:	if line, err := reader.ReadString('\n'); err != nil {
         .          .    226:		log.Printf("conntrack error: %v", err)
         .          .    227:		return
         .          .    228:	} else if line != conntrackOpenTag {
         .          .    229:		log.Printf("conntrack invalid output: '%s'", line)
         .          .    230:		return
         .          .    231:	}
         .          .    232:
         .          .    233:	defer log.Printf("contrack exiting")
         .          .    234:
         .          .    235:	// Now loop on the output stream
         .          .    236:	decoder := xml.NewDecoder(reader)
         .          .    237:	for {
         .          .    238:		var f flow
         .   217.64MB    239:		if err := decoder.Decode(&f); err != nil {
         .          .    240:			log.Printf("conntrack error: %v", err)
         .          .    241:			return
         .          .    242:		}
         .    22.23MB    243:		c.handleFlow(f, false)
         .          .    244:	}
         .          .    245:}
         .          .    246:
         .          .    247:func (c *conntrackWalker) existingConnections() ([]flow, error) {
         .          .    248:	args := append([]string{"-L", "-o", "xml", "-p", "tcp"}, c.args...)
[...]
(pprof) 
```

There are no contrack errors in the logs, and the conntrack processes have been running as long as the probe:

```
$ ps -eo pid,cmd,etime | grep 'conntrack\|scope-probe' 
12244 scope-probe probe -docker=t    11:33:17
12281 conntrack -E -o xml -p tcp     11:33:16
12297 conntrack -E -o xml -p tcp     11:33:16
```

So, similarly to what we saw with the stats, I would say that the problem comes from the [buffered flows](https://github.com/weaveworks/scope/blob/c16f0d7f40091ea42071f79f915e1fe919e6c77c/probe/endpoint/conntrack.go#L313-L318) somehow not being truncated and growing out of hand.

Also, we should either rethink the stats truncation or remove [this line](https://github.com/weaveworks/scope/blob/c16f0d7f40091ea42071f79f915e1fe919e6c77c/probe/docker/container.go#L212) since it's spamming the logs:

```
$ docker logs weavescope |&  grep 'dropping stats' |  wc -l
161482
```

**Comment by tomwilkie** [comment]
> So, similarly to what we saw with the stats, I would say that the problem
comes from the buffered flows
<https://github.com/weaveworks/scope/blob/c16f0d7f40091ea42071f79f915e1fe919e6c77c/probe/endpoint/conntrack.go#L313-L318>
somehow
not being truncated and growing out of hand.

This to me looks like the xml decoder making lots of allocations, not the
buffered flows growing.  But I don't know how to read these traces - does
this count live memory and where it was allocated?  In which case this
would be allocated in the xml decoder but kept live by the buffered flows.
We could time them out I guess, but I'd rather find out why the buffer is
not draining.

> Also, we should either rethink the stats truncation or remove this line
<https://github.com/weaveworks/scope/blob/c16f0d7f40091ea42071f79f915e1fe919e6c77c/probe/docker/container.go#L212>
since
it's spamming the logs:
Now thats interesting - it definitely does not spam the logs for me.  When
does this first occur in the logs?  I'd prefer not to remove this, as any
instance of it is the sign of a real bug.  There should only every be 2
buffered stats per container, as they get drained every second by the
reporter.

It looks like (for some reason) you're probes are not generating reports.
Its the report generation that is supposed to drain the buffered flows and
the stats - so the root cause that would explain both is still alluding us.

Bigger question - what is it about your setup that is triggering all these
issues?  How many containers are their?   How many hosts?  How long are you
running this for?

This also looks like it might be the same issue hit by the JPMC guys, so
this make it (a) not a regression, but an old bug present in 0.11 and (b) a
priority for 0.13.

Thanks for working on this.

**Comment by tomwilkie** [comment]
We were locking up the reporter thread in the weave tagger.  @2opremio has a goroutine dump to prove it.

**Comment by 2opremio** [comment]
Here are the goroutines: https://gist.github.com/2opremio/53573cc2b1dcf121e601

I think we should do three things about this:

1. Fix #889 (obviously)
2. Limit the size of the conntrack buffered flows to a reasonable maximum.
3. Time-box the execution of reporters/taggers or decouple publishing and reporting so that the whole probe doesn't deadlock due to a single reporter/tagger.

**Comment by tomwilkie** [comment]
+1 on (2) & (3).

Instead of time boxing them, I think we should have each one on its own goroutine, trigger a report on the groutine, and then set a timeout for receiving results from them.  It will have the same effect I think.

**Comment by 2opremio** [comment]
Yes, that makes a lot of sense.

**Comment by 2opremio** [comment]
As I mentioned on #889, the deadlock seems to be fixed, but Scope still behaves pretty erratically on ECS, containers appear an disappear all the time.

**Comment by 2opremio** [comment]
Closed via #889
